/* ============================================================
   DREAMSKY HOLIDAY — data.js
   Content for the package detail popup and the blog article popup.
   Loaded before main.js and exposed on window.

   NOTE: itineraries, highlights and article copy below are sample
   editorial content written to real destination geography. Prices are
   intentionally left as "Enquire for Price" everywhere — replace the
   text of any field with DreamSky Holiday's approved final content.
   ============================================================ */
(function () {
  "use strict";

  /* ---------------- PACKAGES ---------------- */
  window.PACKAGE_DATA = {
    "dubai-luxury": {
      name: "Dubai Luxury Escape",
      tag: "Luxury",
      loc: "Dubai, United Arab Emirates",
      duration: "5 Days / 4 Nights",
      nights: "4 nights hotel",
      best: "November – March",
      idealFor: "Couples, families, first-time international travelers",
      price: "Enquire for Price",
      priceNote: "per person",
      img: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1200&auto=format&fit=crop",
      summary:
        "Dubai packs a desert, a beach and one of the world's most photographed skylines into a single short trip. This route balances the headline sights with enough slow time along the marina that it never feels like a race between attractions.",
      highlights: [
        "Evening at Burj Khalifa's observation deck",
        "Red-dune desert safari with BBQ dinner",
        "Dhow cruise dinner along Dubai Creek or Marina",
        "Old Dubai souks — gold, spice and the abra crossing",
        "Free time at Dubai Mall and The Palm",
      ],
      itinerary: [
        { day: "Day 1", title: "Arrival & Marina evening", text: "Arrive in Dubai, transfer to your hotel and check in. The rest of the day is free — an easy first evening is the Marina walk or JBR beachfront, both a short drive from most city hotels." },
        { day: "Day 2", title: "City tour & Burj Khalifa", text: "A half-day city tour covering Jumeirah Mosque from outside, the Burj Al Arab viewpoint, Dubai Frame and Old Dubai's gold and spice souks with an abra ride across the creek. Evening: timed entry to the Burj Khalifa observation deck and the fountain show below." },
        { day: "Day 3", title: "Desert safari", text: "Morning free for Dubai Mall or the aquarium. Afternoon pickup for a red-dune desert safari — dune bashing, camel ride, sandboarding and a desert camp dinner with live entertainment before the drive back." },
        { day: "Day 4", title: "Palm Jumeirah & dhow cruise", text: "Explore The Palm and the monorail run to Atlantis, with optional add-ons like Aquaventure or The View at The Palm. In the evening, a dhow cruise dinner with the skyline lit up on both banks." },
        { day: "Day 5", title: "Departure", text: "Free morning for last-minute shopping depending on your flight time, then transfer to Dubai International Airport for your return journey." },
      ],
      inclusions: [
        "4 nights accommodation on twin-sharing basis",
        "Daily breakfast at the hotel",
        "Airport transfers on a private basis",
        "Half-day city tour with Burj Khalifa entry",
        "Desert safari with BBQ dinner",
        "Dhow cruise dinner",
        "All applicable hotel taxes",
      ],
      exclusions: [
        "Airfare and airport taxes (quoted separately)",
        "UAE visa charges",
        "Lunches, dinners and beverages unless specified",
        "Optional tours and theme-park tickets",
        "Travel insurance, tips and personal expenses",
      ],
    },

    "maldives-retreat": {
      name: "Maldives Ocean Retreat",
      tag: "Honeymoon",
      loc: "Maldives, Indian Ocean",
      duration: "5 Days / 4 Nights",
      nights: "4 nights resort island",
      best: "November – April",
      idealFor: "Honeymooners, anniversaries, quiet getaways",
      price: "Enquire for Price",
      priceNote: "per couple",
      img: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?q=80&w=1200&auto=format&fit=crop",
      summary:
        "One island, one resort, nothing to commute to. This is a deliberately unpacked itinerary — a villa on the water, a house reef a few steps away, and a handful of experiences booked around sunrise and sunset rather than a schedule.",
      highlights: [
        "Overwater or beach villa stay, resort-dependent",
        "Speedboat or seaplane transfer over the atolls",
        "House-reef snorkelling straight off the deck",
        "Sunset dolphin cruise",
        "Private candlelit dinner on the sand",
      ],
      itinerary: [
        { day: "Day 1", title: "Arrival & transfer to the island", text: "Land at Velana International Airport, Malé, where the resort representative meets you. Transfer by speedboat or seaplane depending on the atoll, then villa check-in and a slow first evening." },
        { day: "Day 2", title: "House reef & lagoon", text: "A full day on the island. Snorkel the house reef, take out a kayak or paddleboard, and spend the afternoon between the pool and the lagoon. Optional spa treatment for couples." },
        { day: "Day 3", title: "Sunset cruise", text: "Morning at leisure. Late afternoon dolphin-spotting cruise as the light goes gold, followed by a private candlelit dinner arranged on the beach or your villa deck." },
        { day: "Day 4", title: "Sandbank & water sports", text: "Optional half-day sandbank picnic or a guided snorkelling excursion to a nearby reef. Afternoon free for water sports or simply doing nothing at all." },
        { day: "Day 5", title: "Departure", text: "Breakfast, check out, and the transfer back to Malé in time for your departure flight." },
      ],
      inclusions: [
        "4 nights resort stay on twin-sharing basis",
        "Meal plan as per the selected resort",
        "Return airport–resort transfers (speedboat or seaplane)",
        "Honeymoon inclusions where the resort offers them",
        "Sunset dolphin cruise",
        "All applicable resort taxes and green tax",
      ],
      exclusions: [
        "Airfare and airport taxes (quoted separately)",
        "Meals outside the selected meal plan",
        "Water sports, diving and spa unless specified",
        "Travel insurance, tips and personal expenses",
      ],
    },

    "bali-bliss": {
      name: "Bali Bliss Journey",
      tag: "International",
      loc: "Bali, Indonesia",
      duration: "6 Days / 5 Nights",
      nights: "2 nights Ubud + 3 nights Seminyak/Kuta",
      best: "April – October",
      idealFor: "Couples, friends, first-time Southeast Asia travelers",
      price: "Enquire for Price",
      priceNote: "per person",
      img: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1200&auto=format&fit=crop",
      summary:
        "Bali works best split in two — the green, quiet inland around Ubud first, then the coast. This route does exactly that, so you get rice terraces and temple mornings without giving up beach time at the end.",
      highlights: [
        "Tegallalang rice terraces and the Ubud art villages",
        "Tanah Lot and Uluwatu cliff temples at sunset",
        "Kecak fire dance performance",
        "Nusa Penida or Nusa Dua day trip",
        "Water sports at Tanjung Benoa",
      ],
      itinerary: [
        { day: "Day 1", title: "Arrival in Bali", text: "Arrive at Ngurah Rai International Airport, Denpasar. Transfer inland to Ubud and check in. Evening free to walk the Ubud town centre." },
        { day: "Day 2", title: "Ubud & the rice terraces", text: "Tegallalang rice terraces, a coffee plantation stop, the Ubud monkey forest and the palace and art market. Optional Tegenungan waterfall in the afternoon." },
        { day: "Day 3", title: "Ubud to the coast via Tanah Lot", text: "Check out and drive south, stopping at Taman Ayun and the sea temple at Tanah Lot for sunset before checking in to your beach-side hotel in Seminyak or Kuta." },
        { day: "Day 4", title: "Uluwatu & Kecak dance", text: "A relaxed morning at the beach. Afternoon drive down the Bukit peninsula to Uluwatu temple on the cliff edge, with the Kecak fire dance staged as the sun sets. Seafood dinner at Jimbaran is a popular add-on." },
        { day: "Day 5", title: "Island or water-sports day", text: "Choose a Nusa Penida day trip for the cliff viewpoints and beaches, or stay closer with water sports at Tanjung Benoa — banana boat, jet ski and parasailing." },
        { day: "Day 6", title: "Departure", text: "Free time depending on your flight, then transfer to the airport for your return journey." },
      ],
      inclusions: [
        "5 nights accommodation on twin-sharing basis",
        "Daily breakfast",
        "Private airport and inter-hotel transfers",
        "Sightseeing tours as per the itinerary with driver",
        "Entrance fees for the listed temples and sites",
        "All applicable hotel taxes",
      ],
      exclusions: [
        "Airfare and airport taxes (quoted separately)",
        "Indonesia visa on arrival fee where applicable",
        "Lunches, dinners and beverages",
        "Water sports and optional day trips unless specified",
        "Travel insurance, tips and personal expenses",
      ],
    },

    "swiss-alpine": {
      name: "Swiss Alpine Escape",
      tag: "Luxury",
      loc: "Switzerland",
      duration: "7 Days / 6 Nights",
      nights: "Zurich, Interlaken & Lucerne",
      best: "June – September",
      idealFor: "Couples, families, scenic-rail travelers",
      price: "Enquire for Price",
      priceNote: "per person",
      img: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?q=80&w=1200&auto=format&fit=crop",
      summary:
        "Switzerland rewards travelling slowly by train. This route bases you in two or three towns instead of moving every night, and uses the rail network for the mountain excursions — Jungfraujoch, Titlis and the lake steamers.",
      highlights: [
        "Jungfraujoch — the highest railway station in Europe",
        "Mount Titlis rotating cable car and glacier cave",
        "Lake Lucerne cruise and the Chapel Bridge",
        "Interlaken between Lakes Thun and Brienz",
        "Scenic rail legs between the valley towns",
      ],
      itinerary: [
        { day: "Day 1", title: "Arrival in Zurich", text: "Arrive at Zurich Airport and transfer to your hotel. Evening free to walk the old town and along the Limmat." },
        { day: "Day 2", title: "Zurich to Interlaken", text: "Train through the central valleys to Interlaken, set between two lakes. Afternoon free — the Höhematte park, the lakefront or the Harder Kulm funicular for the first proper mountain view." },
        { day: "Day 3", title: "Jungfraujoch excursion", text: "A full-day rail excursion up to Jungfraujoch via Grindelwald or Lauterbrunnen — the Sphinx observation deck, the Ice Palace and the Aletsch glacier view, weather permitting." },
        { day: "Day 4", title: "Lauterbrunnen & Grindelwald valley", text: "A gentler day in the valleys below — waterfalls at Lauterbrunnen, and either Grindelwald First or Schilthorn as an optional cable-car add-on." },
        { day: "Day 5", title: "Interlaken to Lucerne", text: "Rail transfer to Lucerne. Afternoon in the old town: the Chapel Bridge, the Lion Monument and a cruise on Lake Lucerne." },
        { day: "Day 6", title: "Mount Titlis", text: "Excursion to Engelberg and up Mount Titlis by the rotating cable car, with the glacier cave and cliff walk at the top. Evening back in Lucerne." },
        { day: "Day 7", title: "Departure", text: "Transfer to Zurich Airport for your return flight." },
      ],
      inclusions: [
        "6 nights accommodation on twin-sharing basis",
        "Daily breakfast",
        "Second-class rail travel between the listed towns",
        "Jungfraujoch and Mount Titlis excursion tickets",
        "Lake Lucerne cruise",
        "All applicable hotel taxes",
      ],
      exclusions: [
        "Airfare and airport taxes (quoted separately)",
        "Schengen visa charges",
        "Lunches and dinners",
        "City tourist tax payable at hotels where applicable",
        "Optional cable cars, travel insurance and personal expenses",
      ],
    },

    "thailand-culture": {
      name: "Thailand Culture & Adventure",
      tag: "Adventure",
      loc: "Bangkok, Phuket & Krabi, Thailand",
      duration: "6 Days / 5 Nights",
      nights: "2 nights Bangkok + 3 nights Phuket",
      best: "November – February",
      idealFor: "Friends, families, value-conscious first trips abroad",
      price: "Enquire for Price",
      priceNote: "per person",
      img: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?q=80&w=700&auto=format&fit=crop",
      summary:
        "Two very different halves: Bangkok's temples, markets and street food, then the limestone islands off the Andaman coast. Short domestic flights keep the transfer time down so more of the week is spent actually there.",
      highlights: [
        "Grand Palace and Wat Pho reclining Buddha",
        "Chao Phraya river and a floating-market morning",
        "Phi Phi islands by speedboat",
        "James Bond Island and Phang Nga Bay canoeing",
        "Patong beach and the Big Buddha viewpoint",
      ],
      itinerary: [
        { day: "Day 1", title: "Arrival in Bangkok", text: "Arrive at Suvarnabhumi Airport and transfer to your hotel. Evening free — Asiatique riverfront or the Sukhumvit night markets are easy first stops." },
        { day: "Day 2", title: "Temples & markets", text: "Morning city and temple tour: the Grand Palace, Wat Pho and Wat Traimit. Afternoon free for shopping at MBK or Chatuchak, depending on the day of the week." },
        { day: "Day 3", title: "Bangkok to Phuket", text: "Short domestic flight to Phuket and transfer to your beach hotel. Evening at Patong or a quieter stretch of coast depending on where you stay." },
        { day: "Day 4", title: "Phi Phi islands", text: "Full-day speedboat trip to the Phi Phi group — Maya Bay viewpoint, Pileh lagoon, Monkey Beach and snorkelling stops, with lunch included on the boat or at Phi Phi Don." },
        { day: "Day 5", title: "Phang Nga Bay", text: "James Bond Island and the limestone karsts of Phang Nga Bay, with sea-canoeing through the caves at Hong Island. Afternoon back for the Big Buddha and Karon viewpoint." },
        { day: "Day 6", title: "Departure", text: "Free morning, then transfer to Phuket International Airport for your return journey." },
      ],
      inclusions: [
        "5 nights accommodation on twin-sharing basis",
        "Daily breakfast",
        "Bangkok–Phuket domestic flight",
        "Airport and hotel transfers",
        "Bangkok city and temple tour",
        "Phi Phi and Phang Nga island tours with lunch",
      ],
      exclusions: [
        "International airfare and airport taxes",
        "Thailand visa fee where applicable",
        "Lunches and dinners unless specified",
        "National park fees payable locally on island tours",
        "Travel insurance, tips and personal expenses",
      ],
    },

    "europe-classic": {
      name: "Europe Classic Journey",
      tag: "International",
      loc: "Multi-country, Europe",
      duration: "12 Days / 11 Nights",
      nights: "Paris, Switzerland, Italy & Austria",
      best: "May – September",
      idealFor: "Families, multi-generation groups, first Europe trip",
      price: "Enquire for Price",
      priceNote: "per person",
      img: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?q=80&w=1200&auto=format&fit=crop",
      summary:
        "The classic first Europe route, planned with enough nights in each city that you aren't packing every morning. Paris, the Swiss Alps, northern Italy and an Austrian lake stop, linked by rail and coach.",
      highlights: [
        "Eiffel Tower and a Seine river cruise",
        "Swiss mountain excursion and Lake Lucerne",
        "Venice by vaporetto and St Mark's Square",
        "Florence, Pisa and the Tuscan countryside",
        "Innsbruck and the Austrian Tyrol",
      ],
      itinerary: [
        { day: "Day 1–3", title: "Paris", text: "Arrive and settle in. A city tour covering the Eiffel Tower, Champs-Élysées, Arc de Triomphe and Notre-Dame from outside, a Seine cruise, and a free day for the Louvre or Disneyland Paris." },
        { day: "Day 4–5", title: "Paris to Switzerland", text: "High-speed train to Switzerland. Lake Lucerne, the Chapel Bridge and a full-day mountain excursion — Titlis or Jungfraujoch depending on the season and weather." },
        { day: "Day 6–7", title: "Venice & Verona", text: "Cross into Italy. Venice by vaporetto with St Mark's Square and a Murano glass demonstration, then on via Verona's old centre." },
        { day: "Day 8–9", title: "Florence & Pisa", text: "Florence for the Duomo, Ponte Vecchio and the leather markets, with a half-day to Pisa and the Field of Miracles." },
        { day: "Day 10–11", title: "Innsbruck & the Tyrol", text: "North through the Alps to Innsbruck — the Golden Roof, the old town and an afternoon in the surrounding Tyrolean countryside." },
        { day: "Day 12", title: "Departure", text: "Transfer to the departure airport for your return flight home." },
      ],
      inclusions: [
        "11 nights accommodation on twin-sharing basis",
        "Daily breakfast and selected Indian dinners",
        "Inter-city rail and coach travel as per itinerary",
        "City tours with a tour manager or local guides",
        "Listed entrance tickets and cruises",
        "All applicable hotel taxes",
      ],
      exclusions: [
        "Airfare and airport taxes (quoted separately)",
        "Schengen visa charges and appointment fees",
        "Lunches and meals not specified",
        "City tourist tax payable at hotels",
        "Optional excursions, insurance and personal expenses",
      ],
    },

    "rajasthan-royal": {
      name: "Rajasthan Royal Trail",
      tag: "Domestic",
      loc: "Jaipur, Jodhpur, Jaisalmer & Udaipur",
      duration: "7 Days / 6 Nights",
      nights: "Four heritage cities",
      best: "October – March",
      idealFor: "Families, heritage and photography travelers",
      price: "Enquire for Price",
      priceNote: "per person",
      img: "https://images.unsplash.com/photo-1477587458883-47145ed94245?q=80&w=1200&auto=format&fit=crop",
      summary:
        "Fort cities, painted havelis, a desert camp night and a lake-palace finish in Udaipur — driven end to end so you see the countryside between the cities rather than flying over it.",
      highlights: [
        "Amber Fort and the Jaipur city palace complex",
        "Mehrangarh Fort above the blue city, Jodhpur",
        "Sam sand dunes camel safari and desert camp",
        "Jaisalmer's golden fort and havelis",
        "Lake Pichola boat ride in Udaipur",
      ],
      itinerary: [
        { day: "Day 1", title: "Arrive Jaipur", text: "Arrive in Jaipur and check in. Evening at Birla Mandir or the local bazaars for block prints and juttis." },
        { day: "Day 2", title: "Jaipur sightseeing", text: "Amber Fort in the morning, then the City Palace, Jantar Mantar and a photo stop at Hawa Mahal. Evening light and sound show at Amber, optional." },
        { day: "Day 3", title: "Jaipur to Jodhpur", text: "Drive to Jodhpur, with a stop at Ajmer or Pushkar en route. Evening free at the Clock Tower market." },
        { day: "Day 4", title: "Jodhpur to Jaisalmer", text: "Mehrangarh Fort and Jaswant Thada in the morning, then the drive west into the Thar desert to Jaisalmer." },
        { day: "Day 5", title: "Jaisalmer & the dunes", text: "The living fort, Patwon Ki Haveli and Gadisar Lake. Late afternoon transfer to the Sam dunes for a camel safari, sunset and a night at a desert camp with folk music." },
        { day: "Day 6", title: "Jaisalmer to Udaipur", text: "A long but scenic drive south to Udaipur, arriving by evening. Optional boat ride on Lake Pichola if the light holds." },
        { day: "Day 7", title: "Udaipur & departure", text: "City Palace, Jagdish Temple and Saheliyon Ki Bari in the morning, then transfer to Udaipur airport or railway station." },
      ],
      inclusions: [
        "6 nights accommodation including one desert camp night",
        "Daily breakfast and dinner at the camp",
        "Private air-conditioned vehicle for the full circuit",
        "Driver allowance, tolls, parking and state taxes",
        "Camel safari at Sam dunes",
        "All applicable hotel taxes",
      ],
      exclusions: [
        "Train or air travel to Jaipur and from Udaipur",
        "Monument entrance fees and guide charges",
        "Lunches and dinners unless specified",
        "Camera fees, jeep ride at Amber Fort",
        "Travel insurance, tips and personal expenses",
      ],
    },

    "kashmir-valley": {
      name: "Kashmir Valley Escape",
      tag: "Domestic",
      loc: "Srinagar, Gulmarg & Pahalgam",
      duration: "6 Days / 5 Nights",
      nights: "Houseboat & hotel stays",
      best: "March – October",
      idealFor: "Families, honeymooners, first-time Himalaya travelers",
      price: "Enquire for Price",
      priceNote: "per person",
      img: "https://images.unsplash.com/photo-1566837945700-30057527ade0?q=80&w=1200&auto=format&fit=crop",
      summary:
        "A short, easy Himalayan trip built around three bases — Srinagar's lake, the meadows at Gulmarg and the Lidder valley at Pahalgam — with a night on a Dal Lake houseboat kept as the finish.",
      highlights: [
        "Shikara ride and a houseboat night on Dal Lake",
        "Gulmarg Gondola to Kongdoori and Apharwat",
        "Betaab and Aru valleys near Pahalgam",
        "Mughal gardens — Nishat, Shalimar and Chashme Shahi",
        "Sonmarg and the Thajiwas glacier viewpoint",
      ],
      itinerary: [
        { day: "Day 1", title: "Arrive Srinagar", text: "Arrive at Srinagar airport and transfer to your hotel. Afternoon at the Mughal gardens, then a shikara ride on Dal Lake at sunset." },
        { day: "Day 2", title: "Gulmarg day trip", text: "Drive to Gulmarg through the pine and rice-terrace belt. Gondola phase one to Kongdoori, with phase two to Apharwat subject to weather and availability. Return to Srinagar by evening." },
        { day: "Day 3", title: "Srinagar to Pahalgam", text: "Drive to Pahalgam via the saffron fields at Pampore and the cricket-bat workshops along the way. Afternoon free along the Lidder river." },
        { day: "Day 4", title: "Pahalgam valleys", text: "A local sightseeing day by union-taxi to Betaab valley, Aru valley and Chandanwari — some of the best short walks in the region." },
        { day: "Day 5", title: "Sonmarg & houseboat night", text: "Return towards Srinagar with a day trip to Sonmarg and the Thajiwas glacier viewpoint, then check in to a Dal Lake houseboat for the night." },
        { day: "Day 6", title: "Departure", text: "Breakfast on the houseboat and transfer to Srinagar airport for your onward flight." },
      ],
      inclusions: [
        "5 nights accommodation including one houseboat night",
        "Daily breakfast and dinner",
        "Private vehicle for transfers and sightseeing",
        "Shikara ride on Dal Lake",
        "Driver allowance, tolls and parking",
        "All applicable hotel taxes",
      ],
      exclusions: [
        "Airfare to and from Srinagar",
        "Gulmarg gondola tickets and union taxi charges at Pahalgam and Sonmarg",
        "Pony rides, sledging and local guides",
        "Lunches and beverages",
        "Travel insurance, tips and personal expenses",
      ],
    },
  };

  /* ---------------- BLOG ARTICLES ---------------- */
  window.BLOG_DATA = {
    "first-international-trip": {
      title: "10 Things to Know Before Your First International Trip",
      category: "Travel Tips",
      date: "Sample post",
      read: "6 min read",
      img: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=1200&auto=format&fit=crop",
      excerpt: "A practical checklist for first-time international travelers.",
      body: [
        { type: "p", text: "The first trip abroad is rarely difficult — it's just unfamiliar. Almost everything that goes wrong on a first international holiday traces back to one of a handful of small things nobody mentioned beforehand. Here's the list we walk every first-time traveler through." },
        { type: "h", text: "Before you book" },
        { type: "list", items: [
          "Check your passport validity first, not last. Most countries want at least six months left on the day you travel, counted from your return date.",
          "Understand the visa route before paying for anything non-refundable. Visa-free, visa-on-arrival and e-visa are three different processes with three different lead times.",
          "Match the season to the destination, not to your leave calendar. The same city in the wrong month can be a completely different trip.",
          "Keep the first and last day light. Arrival day and departure day are half days in practice once transfers and check-in times are counted.",
        ]},
        { type: "h", text: "Money, and the bit people forget" },
        { type: "p", text: "Carry a mix: a small amount of local currency for the first day, a forex card for the bulk of your spending, and one credit card kept separately as a backup. Tell your bank you're travelling so the first transaction abroad doesn't trigger a block. And check whether your destination is genuinely card-friendly — parts of Southeast Asia and Europe still run on cash for markets, taxis and small restaurants." },
        { type: "p", text: "Airport currency counters almost always give the worst rate. Change a token amount there if you must, and do the rest in the city." },
        { type: "h", text: "Documents" },
        { type: "list", items: [
          "Keep digital copies of your passport, visa, tickets and insurance in your email and offline on your phone.",
          "Print one paper set. Immigration queues and hotel check-ins are faster when you aren't unlocking a phone with 4% battery.",
          "Carry your hotel address in writing — the local-language version if the script differs from yours.",
        ]},
        { type: "h", text: "Connectivity and the first hour" },
        { type: "p", text: "The first hour after landing is where most stress happens. Sort out data before you leave the airport — an international roaming pack, a local SIM or an eSIM bought in advance. Then confirm your transfer, note the exchange rate on the board, and don't accept an unmarked taxi at the arrivals door." },
        { type: "h", text: "Pack for the trip you're actually taking" },
        { type: "p", text: "Airline baggage limits vary far more on international routes than domestic, and low-cost carriers on short international hops are often hand-baggage only unless you add checked bags in advance. Weigh your bag at home. Keep medication, a change of clothes and chargers in your cabin bag in case the checked bag takes a slower route than you do." },
        { type: "h", text: "Insurance is not optional" },
        { type: "p", text: "Travel insurance costs a fraction of one hospital night abroad, and many visas require it anyway. Read what's covered — medical, baggage delay, trip cancellation — and carry the policy number where you can reach it without internet." },
        { type: "h", text: "And finally: plan less than you think" },
        { type: "p", text: "The most common regret we hear isn't a missed attraction. It's having booked so much that there was no room for the afternoon that turned out to be the best part of the trip. Three anchors a day is plenty." },
      ],
    },

    "perfect-honeymoon": {
      title: "How to Plan the Perfect Honeymoon Escape",
      category: "Honeymoon",
      date: "Sample post",
      read: "5 min read",
      img: "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1200&auto=format&fit=crop",
      excerpt: "What to prioritize when choosing dates, destinations and stays.",
      body: [
        { type: "p", text: "A honeymoon is the one trip where the itinerary matters less than the pacing. Couples who come back happiest almost always made the same three decisions early: fewer destinations, later start, and one splurge instead of five small ones." },
        { type: "h", text: "Give yourself a buffer after the wedding" },
        { type: "p", text: "Flying out the morning after the wedding sounds romantic and rarely is. Two or three days between the last function and the flight turns the first day of the honeymoon into a holiday rather than a recovery. It also gives room for passport, visa or name-change paperwork that runs late." },
        { type: "h", text: "Pick one destination, or two at most" },
        { type: "p", text: "A ten-day honeymoon split across four cities is a sightseeing tour. The classic pairing that works well is one active half and one still half — a city or island-hopping section first, then a resort where nothing is scheduled. Bali and the Maldives, Thailand and Krabi, Switzerland and a lake town all follow that shape." },
        { type: "h", text: "Where the budget actually goes furthest" },
        { type: "list", items: [
          "The room. You will spend more waking time in it than on any tour. A villa with a private pool or a sea-facing balcony changes the whole trip.",
          "One standout meal or private experience, rather than several average ones.",
          "Private transfers instead of shared. Arriving without a ninety-minute hotel-drop loop is worth the difference.",
          "Timing: shoulder season gets you a better room category for the same spend.",
        ]},
        { type: "h", text: "Tell people it's your honeymoon" },
        { type: "p", text: "Say it at booking and again at check-in. Most resorts have honeymoon inclusions they don't advertise — a room upgrade subject to availability, a cake, a decorated bed, a complimentary dinner. None of it is guaranteed, all of it is free to ask for." },
        { type: "h", text: "The practical layer" },
        { type: "p", text: "If a passport is being reissued in a married name, remember the ticket name must match the passport you actually travel on. Book flights in the name on the document you'll carry. Keep the marriage certificate handy for visa applications and hotel bookings made under different surnames." },
        { type: "h", text: "Leave one day genuinely empty" },
        { type: "p", text: "No tour, no booking, no alarm. Ask any couple a year later which day they remember and it's usually that one." },
      ],
    },

    "dubai-guide": {
      title: "A Practical Guide to Planning a Dubai Holiday",
      category: "Destination Guides",
      date: "Sample post",
      read: "7 min read",
      img: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1200&auto=format&fit=crop",
      excerpt: "Best neighborhoods, timing and how many days you actually need.",
      body: [
        { type: "p", text: "Dubai is one of the easiest international trips to organize and one of the easiest to over-plan. The attractions are spread out, the distances look shorter on a map than they drive, and the weather decides more of your schedule than anything else." },
        { type: "h", text: "When to go" },
        { type: "p", text: "November to March is the comfortable window — daytime temperatures suit walking, outdoor dining and desert evenings. April and October are warm but workable if you shift outdoor plans to early morning and after sunset. June to August is intensely hot; it's the cheapest window and it works if your plan is largely malls, indoor attractions and hotel pools." },
        { type: "p", text: "Two things to check against your dates: Ramadan, when daytime dining and entertainment hours change, and the Dubai Shopping Festival window if retail is part of the plan." },
        { type: "h", text: "How many days" },
        { type: "list", items: [
          "Four days: the city tour, Burj Khalifa, a desert safari and a dhow cruise. Tight but complete.",
          "Five to six days: the same, plus The Palm, a theme park or a beach day, and unhurried evenings.",
          "Seven days: adds a day trip to Abu Dhabi for the Sheikh Zayed Grand Mosque, and time for Hatta or a second theme park.",
        ]},
        { type: "h", text: "Where to stay" },
        { type: "p", text: "Downtown puts you within walking distance of Dubai Mall and the fountains — the most convenient base for a first visit. Dubai Marina and JBR suit travelers who want a beach and a walkable evening strip. Deira and Bur Dubai are closer to the souks and the creek and generally cheaper. Palm Jumeirah is a resort stay rather than a base — lovely, but you'll drive for everything else." },
        { type: "h", text: "Getting around" },
        { type: "p", text: "The Metro is clean, cheap and covers the Sheikh Zayed Road corridor well, which is where most of the headline attractions sit. It doesn't reach everywhere, so budget for taxis on the edges. A Nol card covers Metro, tram and bus. Traffic on Sheikh Zayed Road at peak hours is the one thing that reliably breaks a tight schedule." },
        { type: "h", text: "Booking notes that save money" },
        { type: "list", items: [
          "Burj Khalifa tickets are timed and cheaper outside the sunset slot — book in advance either way.",
          "Desert safaris vary enormously. Ask which camp, how long the drive is, and whether dune bashing is included before comparing prices.",
          "Theme-park combo tickets are worth it only if you'll genuinely use both parks.",
          "Alcohol is served in licensed hotel venues; pricing reflects that.",
        ]},
        { type: "h", text: "What people wish they'd known" },
        { type: "p", text: "Dress modestly at mosques and in older neighbourhoods. Carry ID. Everything is air-conditioned to the point of cold, so a light layer is useful even in summer. And leave one evening with nothing planned — the fountain show, a walk along the creek and a plate of food from a small place off the main road is usually the memory that lasts." },
      ],
    },

    "packing-guide": {
      title: "What to Pack for Your Next International Journey",
      category: "Packing",
      date: "Sample post",
      read: "5 min read",
      img: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?q=80&w=1200&auto=format&fit=crop",
      excerpt: "A climate-by-climate packing approach that actually works.",
      body: [
        { type: "p", text: "Packing gets easier once you stop packing for a destination and start packing for a climate. Four climates cover almost every holiday, and each one has a small list that doesn't change." },
        { type: "h", text: "Hot and dry — Dubai, Rajasthan, Egypt" },
        { type: "list", items: [
          "Loose cotton and linen, long sleeves rather than less fabric — it's cooler in direct sun and appropriate at religious sites.",
          "A light layer for aggressive indoor air conditioning.",
          "Sunglasses, high-SPF sunscreen, a hat and lip balm.",
          "Closed shoes for desert evenings, sandals for everything else.",
        ]},
        { type: "h", text: "Hot and humid — Bali, Thailand, Maldives, Singapore" },
        { type: "list", items: [
          "Quick-dry fabrics. Cotton stays wet all day in humidity.",
          "Two swimsuits, so one is always dry.",
          "Reef-safe sunscreen, insect repellent and a dry bag for boat days.",
          "A light rain shell — tropical rain is heavy and brief.",
        ]},
        { type: "h", text: "Cold and alpine — Switzerland, Kashmir, Europe in winter" },
        { type: "p", text: "Layers beat bulk. A thermal base, a fleece or wool mid-layer and a windproof outer shell handle a far wider temperature range than one heavy coat, and they pack smaller. Add gloves, a beanie, warm socks and shoes with actual grip — snow-melt on stone is slipperier than snow." },
        { type: "h", text: "Mixed — multi-country Europe" },
        { type: "p", text: "Pick one colour family so everything works together, pack for five days and plan to do laundry once. Comfortable walking shoes matter more than any other single item; European sightseeing days routinely run to fifteen thousand steps." },
        { type: "h", text: "The bag that matters most" },
        { type: "p", text: "Your cabin bag should be able to survive a day without the checked one: medication with prescriptions, a change of clothes, chargers and adapters, documents, valuables and anything you can't replace locally. Never check power banks — most airlines prohibit them in hold luggage." },
        { type: "h", text: "The short universal list" },
        { type: "list", items: [
          "Universal adapter and a multi-port charger",
          "Power bank in your cabin bag",
          "Basic medicines: painkiller, antacid, antihistamine, rehydration salts, plasters",
          "Copies of passport, visa and insurance — digital and paper",
          "A foldable tote for the things you'll buy",
        ]},
        { type: "p", text: "One last habit worth keeping: weigh the bag at home, full, before you leave. Airport excess-baggage counters charge by the kilo and nobody has ever enjoyed repacking on the terminal floor." },
      ],
    },
  };
})();
